/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cdxt_doctor_base_util_SecretUtil */

#ifndef _Included_com_black_base_util_SecretUtil
#define _Included_com_black_base_util_SecretUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cdxt_doctor_base_util_SecretUtil
 * Method:    getCertificate
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_black_base_util_SecretUtil_getCertificate
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
