package com.black.base.util

object RouterConstData {
    const val WEB_VIEW = "fbsex://webview"
    const val CAPTURE = "fbsex://capture"
    const val SHOW_BIG_IMAGE = "fbsex://showBigImage"
    const val PUBLIC_CHAT_GROUP = "fbsex://publicChatGroup"

    const val IM_GROUP_MEMBER = "fbsex://imGroupMember"
    const val IM_CHAT_ROOM_INFO = "fbsex://imChatRoomInfo"
    const val IM_MODIFY_NAME_CARD = "fbsex://imModifyNameCard"
    const val IM_MODIFY_GROUP = "fbsex://imModifyGroup"
    const val IM_MODIFY_GROUP_NOTICE = "fbsex://imModifyGroupNotice"
    const val IM_CHAT_ROOM_MEMBER_LIST = "fbsex://imGroupMemberList"

    const val NOTICE_CENTER = "fbsex://noticeCenter"
    const val NOTICE_DETAIL = "fbsex://noticeDetail"
    const val ABOUT = "fbsex://about"
    const val ACCOUNT_PROTECT = "fbsex://accountProtect"
    const val ENTRUST_RECORDS = "fbsex://entrustRecords"
    const val ENTRUST_RECORDS_NEW = "fbsex://tradeorder"
    const val ENTRUST_DETAIL = "fbsex://entrustDetail"
    const val SYSTEM_SETTING = "fbsex://systemSetting"
    const val QUOTATION_DETAIL = "fbsex://quotationDetail"
    const val CHOOSE_COUNTRY = "fbsex://chooseCountry"
    const val AD_CENTER = "fbsex://adCenter"
    const val NEWS_DETAIL = "fbsex://newsDetail"
    const val K_LINE_FULL = "fbsex://kLineFull"
    const val LANGUAGE_SETTING = "fbsex://languageSetting"
    const val EXCHANGE_RATES = "fbsex://exchanegRates"
    const val NOTIFICATION_LIST = "fbsex://notificationList"
    const val FINGER_PRINT_CHECK = "fbsex://fingerPrintCheck"
    const val FORUM = "fbsex://forum"

    const val START_PAGE = "fbsex://startPage"
    const val GUID = "fbsex://guid"
    const val HOME_PAGE = "fbsex://homePage"
    const val DEAR_PAIR_SEARCH = "fbsex://dearPairSearch"
    const val MINE = "fbsex://mine"

    const val LOGIN = "fbsex://login"
    const val REGISTER = "fbsex://register"
    const val FORGET_PASSWORD = "fbsex://forgetPassword"
    const val GESTURE_PASSWORD_CHECK = "fbsex://gesturePasswordCheck"
    const val GESTURE_PASSWORD_SETTING = "fbsex://gesturePasswordSetting"
    const val SAFE_CENTER = "fbsex://safeCenter"
    const val GOOGLE_GET_KEY = "fbsex://googleGetKey"
    const val GOOGLE_BIND = "fbsex://googleBind"
    const val GOOGLE_SECURITY_STATUS = "fbsex://googleSecurityStatus"
    const val PHONE_BIND = "fbsex://phoneBind"
    const val PHONE_SECURITY_STATUS = "fbsex://phoneSecurityStatus"
    const val EMAIL_BIND = "fbsex://emailBind"
    const val EMAIL_SECURITY_STATUS = "fbsex://emailSecurityStatus"
    const val RECOMMEND = "fbsex://recommend"
    const val RECOMMEND_RECORD = "fbsex://recommendRecord"
    const val RECOMMEND_PEOPLE = "fbsex://recommendPeople"
    const val RECOMMEND_REWARD_RECORD = "fbsex://recommendRewardRecord"
    const val REAL_NAME_MENU = "fbsex://realNameMenu"
    const val REAL_NAME_INFO = "fbsex://realNameInfo"
    const val REAL_NAME_AUTHENTICATE = "fbsex://realNameAuthenticate"
    const val REAL_NAME_AUTHENTICATE_FIRST = "fbsex://realNameAuthenticateFirst"
    const val REAL_NAME_AUTHENTICATE_SECOND = "fbsex://realNameAuthenticateSecond"
    const val PERSON_INFO_CENTER = "fbsex://personInfoCenter"
    const val CHANGE_PASSWORD = "fbsex://changePassword"
    const val USER_SETTING = "fbsex://userSetting"
    const val NICK_NAME_CHANGE = "fbsex://nickNameChange"

    const val ACCOUNT_MANAGER = "fbsex://accountManager"
    const val MONEY_PASSWORD = "fbsex://moneyPassword"
    const val PAYMENT_METHOD_MANAGER = "fbsex://paymentMethodManager"
    const val PAYMENT_METHOD_TYPE_CHOOSE = "fbsex://paymentMethodTypeChoose"
    const val PAYMENT_METHOD_ADD = "fbsex://paymentMethodAdd"

    const val WALLET = "fbsex://wallet"
    const val FINANCIAL_RECORD = "fbsex://financialRecord"
    const val EXTRACT = "fbsex://extract"
    const val WALLET_CHOOSE_COIN = "fbsex://walletChooseCoin"
    const val WALLET_ADDRESS_MANAGE = "fbsex://walletAddressManage"
    const val WITHDRAW_DETAIL = "fbsex://withdrawDetail"
    const val WALLET_COIN_DETAIL = "fbsex://walletCoinDetail"
    const val WALLET_ADDRESS_ADD = "fbsex://walletAddressAdd"
    const val RECHARGE_DETAIL = "fbsex://rechargeDetail"
    const val WALLET_DETAIL = "fbsex://coinbill"
    const val RECHARGE = "fbsex://recharge"
    const val PUSH_SETTING = "fbsex://push_setting"
    const val WALLET_TRANSFER = "fbsex://walletTransfer"
    const val LEVER_PAIR_CHOOSE = "fbsex://leverPairChoose"
    const val ASSET_TRANSFER = "fbsex://assetTransfer"
    const val WALLET_TRANSFER_RECORD = "fbsex://walletTransferRecord"
    const val LEVER_BORROW = "fbsex://leverBorrow"
    const val LEVER_BORROW_RECORD = "fbsex://leverBorrowRecord"
    const val LEVER_BACK = "fbsex://leverBack"
    const val LEVER_BACK_RECORD = "fbsex://leverBackRecord"
    const val WALLET_LEVER_DETAIL = "fbsex://walletLeverDetail"

    const val PROMOTIONS = "fbsex://fbsIEO"
    const val PROMOTIONS_RECORD = "fbsex://promotionsRecord"
    const val PROMOTIONS_BUY = "fbsex://purchase"
    const val PROMOTIONS_BUY_DETAIL = "fbsex://promotionsBuyDetail"
    const val PROMOTIONS_BUY_RECORD = "fbsex://promotionsBuyRecord"
    const val PROMOTIONS_BUY_FIVE = "fbsex://fivepurchase"
    const val PROMOTIONS_BUY_FIVE_DETAIL = "fbsex://promotionsBuyFiveDetail"
    const val PROMOTIONS_BUY_FIVE_RECORD = "fbsex://promotionsBuyFiveRecord"
    const val DEMAND_RECORD = "fbsex://demandRecord"
    const val DEMAND_CHANGE_OUT = "fbsex://demandChangeOut"
    const val REGULAR_LOCK = "fbsex://regularLock"
    const val REGULAR_HISTORY = "fbsex://regularHistory"
    const val REGULAR_DETAIL = "fbsex://regularDetail"
    const val DEMAND_DETAIL = "fbsex://demandDetail"
    const val MONEY_RECORD = "fbsex://moneyRecord"
    const val LOAN_CONFIG = "fbsex://loanConfig"
    const val LOAN_CREATE = "fbsex://loanCreate"
    const val LOAN_RECORD = "fbsex://loanRecord"
    const val LOAN_ADD_DEPOSIT = "fbsex://loanAddDeposit"
    const val LOAN_BACK = "fbsex://loanBack"
    const val DEMAND_HOME = "fbsex://demandHome"
    const val REGULAR_HOME = "fbsex://regularHome"
    const val LOAN_ADD_DEPOSIT_RECORD = "fbsex://loanAddDepositRecord"
    const val LOAN_ORDER_DETAIL = "fbsex://loanOrderDetail"
    const val CLOUD_POWER_PROJECT = "fbsex://cloudPowerProject"
    const val CLOUD_POWER_RECORD = "fbsex://cloudPowerRecord"

    const val C2C = "fbsex://c2c_old"
    const val C2C_NEW = "fbsex://c2c"

    const val C2C_ORDER = "fbsex://c2cOrder"
    const val C2C_ORDER_DETAIL = "fbsex://c2cOrderDetail"
    const val C2C_ORDER_DETAIL_TALK = "fbsex://c2cOrderDetailTalk"
    const val C2C_ORDER_DETAIL_TALK_NEW = "fbsex://c2cOrderDetailTalkNew"

    const val TRANSACTION = "fbsex://transaction"
    const val C2C_HOME = "fbsex://c2cHome"

    const val FACTION_LIST = "fbsex://league"
    const val FACTION_DETAIL = "fbsex://factionDetail"
    const val FACTION_CHAT = "fbsex://factionChat"

    const val RED_PACKET = "fbsex://openRedPacket"
    const val RED_PACKET_DETAIL = "fbsex://redPacketDetail"
    const val RED_PACKET_CREATE = "fbsex://redPacketCreate"
}