package com.black.base.util

object RouterConstData {
    const val WEB_VIEW = "fiex://webview"
    const val CAPTURE = "fiex://capture"
    const val SHOW_BIG_IMAGE = "fiex://showBigImage"
    const val PUBLIC_CHAT_GROUP = "fiex://publicChatGroup"

    const val IM_GROUP_MEMBER = "fiex://imGroupMember"
    const val IM_CHAT_ROOM_INFO = "fiex://imChatRoomInfo"
    const val IM_MODIFY_NAME_CARD = "fiex://imModifyNameCard"
    const val IM_MODIFY_GROUP = "fiex://imModifyGroup"
    const val IM_MODIFY_GROUP_NOTICE = "fiex://imModifyGroupNotice"
    const val IM_CHAT_ROOM_MEMBER_LIST = "fiex://imGroupMemberList"

    const val NOTICE_CENTER = "fiex://noticeCenter"
    const val NOTICE_DETAIL = "fiex://noticeDetail"
    const val ABOUT = "fiex://about"
    const val ACCOUNT_PROTECT = "fiex://accountProtect"
    const val ENTRUST_RECORDS = "fiex://entrustRecords"
    const val ENTRUST_RECORDS_NEW = "fiex://tradeorder"
    const val ENTRUST_DETAIL = "fiex://entrustDetail"
    const val SYSTEM_SETTING = "fiex://systemSetting"
    const val QUOTATION_DETAIL = "fiex://quotationDetail"
    const val CHOOSE_COUNTRY = "fiex://chooseCountry"
    const val AD_CENTER = "fiex://adCenter"
    const val NEWS_DETAIL = "fiex://newsDetail"
    const val K_LINE_FULL = "fiex://kLineFull"
    const val LANGUAGE_SETTING = "fiex://languageSetting"
    const val EXCHANGE_RATES = "fiex://exchanegRates"
    const val NOTIFICATION_LIST = "fiex://notificationList"
    const val FINGER_PRINT_CHECK = "fiex://fingerPrintCheck"
    const val FORUM = "fiex://forum"

    const val START_PAGE = "fiex://startPage"
    const val GUID = "fiex://guid"
    const val HOME_PAGE = "fiex://homePage"
    const val DEAR_PAIR_SEARCH = "fiex://dearPairSearch"
    const val MINE = "fiex://mine"

    const val LOGIN = "fiex://login"
    const val REGISTER = "fiex://register"
    const val FORGET_PASSWORD = "fiex://forgetPassword"
    const val FORGET_PASSWORD_FIEX = "fiex://forgetPasswordFiex"
    const val FORGET_PASSWORD_NEW_PWD = "fiex://forgetPasswordNewPws"
    const val GESTURE_PASSWORD_CHECK = "fiex://gesturePasswordCheck"
    const val GESTURE_PASSWORD_SETTING = "fiex://gesturePasswordSetting"
    const val SAFE_CENTER = "fiex://safeCenter"
    const val GOOGLE_GET_KEY = "fiex://googleGetKey"
    const val GOOGLE_BIND = "fiex://googleBind"
    const val SAFE_BIND = "fiex://safeBind"
    const val SAFE_UNUSED = "fiex://safeUnuse"
    const val GOOGLE_SECURITY_STATUS = "fiex://googleSecurityStatus"
    const val PHONE_BIND = "fiex://phoneBind"
    const val PHONE_SECURITY_STATUS = "fiex://phoneSecurityStatus"
    const val EMAIL_BIND = "fiex://emailBind"
    const val EMAIL_SECURITY_STATUS = "fiex://emailSecurityStatus"
    const val RECOMMEND = "fiex://recommend"
    const val RECOMMEND_RECORD = "fiex://recommendRecord"
    const val RECOMMEND_PEOPLE = "fiex://recommendPeople"
    const val RECOMMEND_REWARD_RECORD = "fiex://recommendRewardRecord"
    const val REAL_NAME_MENU = "fiex://realNameMenu"
    const val REAL_NAME_INFO = "fiex://realNameInfo"
    const val REAL_NAME_AUTHENTICATE = "fiex://realNameAuthenticate"
    const val REAL_NAME_AUTHENTICATE_FIRST = "fiex://realNameAuthenticateFirst"
    const val REAL_NAME_AUTHENTICATE_SECOND = "fiex://realNameAuthenticateSecond"
    const val PERSON_INFO_CENTER = "fiex://personInfoCenter"
    const val CHANGE_PASSWORD = "fiex://changePassword"
    const val USER_SETTING = "fiex://userSetting"
    const val NICK_NAME_CHANGE = "fiex://nickNameChange"

    const val ACCOUNT_MANAGER = "fiex://accountManager"
    const val MONEY_PASSWORD = "fiex://moneyPassword"
    const val PAYMENT_METHOD_MANAGER = "fiex://paymentMethodManager"
    const val PAYMENT_METHOD_TYPE_CHOOSE = "fiex://paymentMethodTypeChoose"
    const val PAYMENT_METHOD_ADD = "fiex://paymentMethodAdd"

    const val WALLET = "fiex://wallet"
    const val FINANCIAL_RECORD = "fiex://financialRecord"
    const val SPOT_BILL_ACTIVITY = "fiex://spot_bill_activity"
    const val CONTRACT_BILL_ACTIVITY = "fiex://contract_bill_activity"
    const val EXTRACT = "fiex://extract"
    const val WALLET_CHOOSE_COIN = "fiex://walletChooseCoin"
    const val WALLET_ADDRESS_MANAGE = "fiex://walletAddressManage"
    const val WITHDRAW_DETAIL = "fiex://withdrawDetail"
    const val WALLET_COIN_DETAIL = "fiex://walletCoinDetail"
    const val WALLET_ADDRESS_ADD = "fiex://walletAddressAdd"
    const val RECHARGE_DETAIL = "fiex://rechargeDetail"
    const val WALLET_DETAIL = "fiex://coinbill"
    const val RECHARGE = "fiex://recharge"
    const val PUSH_SETTING = "fiex://push_setting"
    const val WALLET_TRANSFER = "fiex://walletTransfer"
    const val LEVER_PAIR_CHOOSE = "fiex://leverPairChoose"
    const val ASSET_TRANSFER = "fiex://assetTransfer"
    const val WALLET_TRANSFER_RECORD = "fiex://walletTransferRecord"
    const val LEVER_BORROW = "fiex://leverBorrow"
    const val LEVER_BORROW_RECORD = "fiex://leverBorrowRecord"
    const val LEVER_BACK = "fiex://leverBack"
    const val LEVER_BACK_RECORD = "fiex://leverBackRecord"
    const val WALLET_LEVER_DETAIL = "fiex://walletLeverDetail"

    const val PROMOTIONS = "fiex://fbsIEO"
    const val PROMOTIONS_RECORD = "fiex://promotionsRecord"
    const val PROMOTIONS_BUY = "fiex://purchase"
    const val PROMOTIONS_BUY_DETAIL = "fiex://promotionsBuyDetail"
    const val PROMOTIONS_BUY_RECORD = "fiex://promotionsBuyRecord"
    const val PROMOTIONS_BUY_FIVE = "fiex://fivepurchase"
    const val PROMOTIONS_BUY_FIVE_DETAIL = "fiex://promotionsBuyFiveDetail"
    const val PROMOTIONS_BUY_FIVE_RECORD = "fiex://promotionsBuyFiveRecord"
    const val DEMAND_RECORD = "fiex://demandRecord"
    const val DEMAND_CHANGE_OUT = "fiex://demandChangeOut"
    const val REGULAR_LOCK = "fiex://regularLock"
    const val REGULAR_HISTORY = "fiex://regularHistory"
    const val REGULAR_DETAIL = "fiex://regularDetail"
    const val DEMAND_DETAIL = "fiex://demandDetail"
    const val MONEY_RECORD = "fiex://moneyRecord"
    const val LOAN_CONFIG = "fiex://loanConfig"
    const val LOAN_CREATE = "fiex://loanCreate"
    const val LOAN_RECORD = "fiex://loanRecord"
    const val LOAN_ADD_DEPOSIT = "fiex://loanAddDeposit"
    const val LOAN_BACK = "fiex://loanBack"
    const val DEMAND_HOME = "fiex://demandHome"
    const val REGULAR_HOME = "fiex://regularHome"
    const val LOAN_ADD_DEPOSIT_RECORD = "fiex://loanAddDepositRecord"
    const val LOAN_ORDER_DETAIL = "fiex://loanOrderDetail"
    const val CLOUD_POWER_PROJECT = "fiex://cloudPowerProject"
    const val CLOUD_POWER_RECORD = "fiex://cloudPowerRecord"

    const val C2C = "fiex://c2c_old"
    const val C2C_NEW = "fiex://c2c"
    const val C2C_QIULK = "fiex://c2c_old"

    const val C2C_ORDER = "fiex://c2cOrder"
    const val C2C_BUY = "fiex://c2cBuy"
    const val C2C_BUYER = "fiex://c2cBuyer"
    const val C2C_PAY_FOR = "fiex://c2cPayFor"
    const val C2C_BUYER_PAY = "fiex://c2cBuyerPay"
    const val C2C_SELL = "fiex://c2cSell"
    const val C2C_PAY = "fiex://c2cPay"
    const val C2C_PAY2 = "fiex://c2cPay2"
    const val C2C_WAITE1 = "fiex://c2cWaite1"
    const val C2C_WAITE2 = "fiex://c2cWaite2"
    const val C2C_ALI = "fiex://c2cAli"
    const val C2C_WEIXIN = "fiex://c2cWechat"
    const val C2C_CARDS = "fiex://c2cCards"
    const val C2C_MINE = "fiex://c2cMine"
    const val C2C_ORDERS = "fiex://c2cOrders"
    const val C2C_CONFRIM = "fiex://c2cConfirm"
    const val C2C_ORDER_DETAIL = "fiex://c2cOrderDetail"
    const val C2C_ORDER_DETAIL_TALK = "fiex://c2cOrderDetailTalk"
    const val C2C_ORDER_DETAIL_TALK_NEW = "fiex://c2cOrderDetailTalkNew"

    const val TRANSACTION = "fiex://transaction"
    const val HOME_CONTRACT = "fiex://contract"
    const val HOME_ASSET = "fiex://homeAsset"
    const val C2C_HOME = "fiex://c2cHome"

    const val FACTION_LIST = "fiex://league"
    const val FACTION_DETAIL = "fiex://factionDetail"
    const val FACTION_CHAT = "fiex://factionChat"

    const val RED_PACKET = "fiex://openRedPacket"
    const val RED_PACKET_DETAIL = "fiex://redPacketDetail"
    const val RED_PACKET_CREATE = "fiex://redPacketCreate"
}